
package com.nextlabs.em.windchill.wsclient;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "QueryAgent", targetNamespace = "http://windchill.em.nextlabs.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface QueryAgent {


    /**
     * 
     * @param requestId
     * @param paras
     * @param reserved
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod(operationName = "Eval")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Eval", targetNamespace = "http://windchill.em.nextlabs.com/", className = "com.nextlabs.em.windchill.wsclient.Eval")
    @ResponseWrapper(localName = "EvalResponse", targetNamespace = "http://windchill.em.nextlabs.com/", className = "com.nextlabs.em.windchill.wsclient.EvalResponse")
    public List<String> eval(
        @WebParam(name = "requestId", targetNamespace = "")
        String requestId,
        @WebParam(name = "paras", targetNamespace = "")
        List<String> paras,
        @WebParam(name = "reserved", targetNamespace = "")
        String reserved);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.nextlabs.em.windchill.wsclient.ObjectAttrCollection
     */
    @WebMethod(operationName = "QueryOid")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "QueryOid", targetNamespace = "http://windchill.em.nextlabs.com/", className = "com.nextlabs.em.windchill.wsclient.QueryOid")
    @ResponseWrapper(localName = "QueryOidResponse", targetNamespace = "http://windchill.em.nextlabs.com/", className = "com.nextlabs.em.windchill.wsclient.QueryOidResponse")
    public ObjectAttrCollection queryOid(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.nextlabs.em.windchill.wsclient.ObjectAttrCollection
     */
    @WebMethod(operationName = "QueryUser")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "QueryUser", targetNamespace = "http://windchill.em.nextlabs.com/", className = "com.nextlabs.em.windchill.wsclient.QueryUser")
    @ResponseWrapper(localName = "QueryUserResponse", targetNamespace = "http://windchill.em.nextlabs.com/", className = "com.nextlabs.em.windchill.wsclient.QueryUserResponse")
    public ObjectAttrCollection queryUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.nextlabs.em.windchill.wsclient.ObjectAttrCollection
     */
    @WebMethod(operationName = "QueryTest")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "QueryTest", targetNamespace = "http://windchill.em.nextlabs.com/", className = "com.nextlabs.em.windchill.wsclient.QueryTest")
    @ResponseWrapper(localName = "QueryTestResponse", targetNamespace = "http://windchill.em.nextlabs.com/", className = "com.nextlabs.em.windchill.wsclient.QueryTestResponse")
    public ObjectAttrCollection queryTest(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

}
