package com.nextlabs.em.windchill.wsclient;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import com.nextlabs.EntitlementManagerContext;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.6 in JDK 6 Generated
 * source version: 2.1
 * 
 */
@WebServiceClient(name = "QueryAgent", targetNamespace = "http://www.nextlabs.com/windchill/QueryAgent", wsdlLocation = "http://localhost/Windchill/com/nextlabs/QueryAgent?wsdl")
public class QueryAgent_Service extends Service {

	EntitlementManagerContext ectx = new EntitlementManagerContext();
	private final static URL QUERYAGENT_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(QueryAgent_Service.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.nextlabs.em.windchill.wsclient.QueryAgent_Service.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://localhost/Windchill/com/nextlabs/QueryAgent?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost/Windchill/com/nextlabs/QueryAgent?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		QUERYAGENT_WSDL_LOCATION = url;
	}

	public QueryAgent_Service(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public QueryAgent_Service() {
		super(QUERYAGENT_WSDL_LOCATION, new QName(
				"http://www.nextlabs.com/windchill/QueryAgent", "QueryAgent"));

	}

	/**
	 * 
	 * @return returns QueryAgent
	 */
	@WebEndpoint(name = "QueryAgentImplPort")
	public QueryAgent getQueryAgentImplPort() {
		QueryAgent qa = null;

		logger.info("QueryAgent_Service EVENT starts");
		try {
			qa = super.getPort(new QName(
					"http://www.nextlabs.com/windchill/QueryAgent",
					"QueryAgentImplPort"), QueryAgent.class);
			logger.info("QueryAgent_Service EVENT qa is " + qa);
		} catch (Exception e) {
			logger.info("QueryAgent_Service EVENT exception is "
					+ e.getMessage());

		}
		return qa;
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns QueryAgent
	 */
	@WebEndpoint(name = "QueryAgentImplPort")
	public QueryAgent getQueryAgentImplPort(WebServiceFeature... features) {
		return super.getPort(new QName(
				"http://www.nextlabs.com/windchill/QueryAgent",
				"QueryAgentImplPort"), QueryAgent.class, features);
	}

}
